[package]
name = "vector-x"
authors = ["Jaydon Yeany"]
description = "A simple crate for fixed-size vectors"
license-file = "LICENSE.txt"
readme = "README.md"
version = "0.1.3"
edition = "2024"

[dependencies]
